### ISSUE TITLE
Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized

### ISSUE THREAD

**Issue by Roy214** [rajch/weave#6] opened 2024-06-01 15:18 UTC
### What happened?

Right after installing kubernetes control plane  using `kubeadm` and `weave net` as network plugin the API server goes down with the below error msg.
```
[root@kubemaster ~]# kubectl get pods -A --watch
error: Get "https://10.74.250.78:6443/api/v1/pods?limit=500": dial tcp 10.74.250.78:6443: connect: connection refused - error from a previous attempt: read tcp 10.74.250.78:44740->10.74.250.78:6443: read: connection reset by peer
[root@kubemaster ~]#  
```

### What did you expect to happen?

The cluster should be working fine with `weave net` 

### How can we reproduce it (as minimally and precisely as possible)?

```
kubeadm init --pod-network-cidr=10.10.0.0/16 --apiserver-advertise-address=10.74.250.78 --v=5

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join 10.74.250.78:6443 --token 7l1k0v.gnzdt2i4a0hg6uaq \
	--discovery-token-ca-cert-hash sha256:9f307309f8fd825a99a30e2643a59159499d4fd78843ac14d0c78f85849da411 
[root@kubemaster ~]# 
[root@kubemaster ~]# export KUBECONFIG=/etc/kubernetes/admin.conf
[root@kubemaster ~]# 
```

```
[root@kubemaster ~]# kubectl apply -f weave-daemonset-k8s.yaml
serviceaccount/weave-net created
clusterrole.rbac.authorization.k8s.io/weave-net created
clusterrolebinding.rbac.authorization.k8s.io/weave-net created
role.rbac.authorization.k8s.io/weave-net created
rolebinding.rbac.authorization.k8s.io/weave-net created
daemonset.apps/weave-net created
[root@kubemaster ~]#
```
```
[root@kubemaster ~]# kubectl get pods -A  --watch
NAMESPACE     NAME                                 READY   STATUS             RESTARTS        AGE
kube-system   coredns-7db6d8ff4d-6t5cb             0/1     Pending            0               3m25s
kube-system   coredns-7db6d8ff4d-z9lvq             0/1     Pending            0               3m25s
kube-system   etcd-kubemaster                      1/1     Running            173 (90s ago)   58s
kube-system   kube-apiserver-kubemaster            1/1     Running            174 (72s ago)   3m59s
kube-system   kube-controller-manager-kubemaster   1/1     Running            12 (112s ago)   4m33s
kube-system   kube-proxy-jgnb6                     0/1     CrashLoopBackOff   2 (7s ago)      3m25s
kube-system   kube-scheduler-kubemaster            0/1     CrashLoopBackOff   181 (30s ago)   58s
kube-system   weave-net-fdvrk                      0/2     Pending            0               8s
kube-system   kube-scheduler-kubemaster            0/1     Running            182 (53s ago)   81s
kube-system   kube-proxy-jgnb6                     1/1     Running            3 (32s ago)     3m50s
kube-system   kube-scheduler-kubemaster            0/1     Completed          182 (61s ago)   89s
kube-system   kube-scheduler-kubemaster            0/1     CrashLoopBackOff   182 (2s ago)    90s
^C[root@kubemaster ~]# 

```

 Error:
====================
```
Jun  1 09:35:45 kubemaster kubelet[15562]: E0601 09:35:45.262058   15562 kubelet.go:2900] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun  1 09:35:46 kubemaster kubelet[15562]: E0601 09:35:46.177829   15562 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://10.74.250.78:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/kubemaster?timeout=10s\": dial tcp 10.74.250.78:6443: connect: connection refused" interval="7s"
```

### Kubernetes version

<details>

```console
[root@kubemaster ~]# kubectl version
Client Version: v1.30.1
```

## Logs:

```
[root@kubemaster ~]# kubectl logs weave-net-fdvrk -n kubesystem
The connection to the server 10.74.250.78:6443 was refused - did you specify the right host or port?
[root@kubemaster ~]# 

Jun  1 09:35:45 kubemaster kubelet[15562]: E0601 09:35:45.262058   15562 kubelet.go:2900] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Jun  1 09:35:46 kubemaster kubelet[15562]: E0601 09:35:46.177829   15562 controller.go:145] "Failed to ensure lease exists, will retry" err="Get \"https://10.74.250.78:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/kubemaster?timeout=10s\": dial tcp 10.74.250.78:6443: connect: connection refused" interval="7s"

```

## Network:

```
[root@kubemaster ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1a:4a:00:02:88 brd ff:ff:ff:ff:ff:ff
    altname enp0s7
    inet 10.74.250.78/21 brd 10.74.255.255 scope global dynamic noprefixroute ens7
       valid_lft 76103sec preferred_lft 76103sec
    inet6 2620:52:0:4af8:68b2:df24:1b39:94f6/64 scope global dynamic noprefixroute 
       valid_lft 2591998sec preferred_lft 604798sec
    inet6 fe80::5ac1:a160:5566:3716/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
[root@kubemaster ~]# 

Firewall is off
```

**Comment by rajch** [comment] 2024-06-02 07:53
From your output above, the weave net pod has not been scheduled at all, so no weave code has run. Your scheduler and proxy seem to be repeatedly crashing. This does not seem to be a problem caused by weave net.

Could you take a look at the logs of the `kube-scheduler-kubemaster` and `kube-proxy-jgnb6`?

**Comment by rajch** [comment] 2024-08-22 07:45
Closing the issue.

**Closed by rajch** 2024-08-22 07:45 UTC
